# Combining Datasets with pandas

## Learning Objectives

At the end of this notebook you should be able to
- combine DataFrames with pandas
- describe the different joining methods (how to join DataFrames)

Pandas functions that allow us to combine two sets of data include the use of `pd.merge()`, `df.join()`, `df.merge()`, and `pd.concat()`. For the most part, these do largely the same things (although you'll notice the slight syntax difference with `merge()` and `concat()` being able to be called via the pandas module and `merge()` and `join()` being able to be called on a DataFrame instance). There are some cases where one of these might be better than another in terms of writing less code or performing some kind of data combination in an easier way. The major differences between these, though, largely depend on what they do by default when you try to combine different data. By default, `merge()` looks to join on common columns, `join()` on common indices, and `concat()` by just appending on a given axis.

You can find more detail about the differences between all three of these in the [docs](https://pandas.pydata.org/pandas-docs/stable/user_guide/merging.html). We'll look at some examples below.

In [2]:
# We'll go back to our wine data set. Who doesn't love wine?
import pandas as pd
wine_df = pd.read_csv('data/winequality-red.csv', delimiter=';')
wine_df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

In [3]:
# A glance at the values of the quality of wine in the DataFrame
wine_df.quality.unique()

array([5, 6, 7, 4, 8, 3])

In [4]:
# get_dummies is a method called on the pandas module - you simply pass in a pandas Series 
# or DataFrame, and it will convert a categorical variable into dummy/indicator variables. 
quality_dummies = pd.get_dummies(wine_df.quality, prefix='quality')
quality_dummies.head()

   quality_3  quality_4  quality_5  quality_6  quality_7  quality_8
0      False      False       True      False      False      False
1      False      False       True      False      False      False
2      False      False       True      False      False      False
3      False      False      False       True      False      False
4      False      False       True      False      False      False

Now let's look at the `join()` method. Remember, this joins on indices by default. This means that we can simply join our quality dummies DataFrame back to our original wine DataFrame with the following...

In [5]:
joined_df = wine_df.join(quality_dummies)
joined_df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,quality_3,quality_4,quality_5,quality_6,quality_7,quality_8
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,False,False,True,False,False,False
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5,False,False,True,False,False,False
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5,False,False,True,False,False,False
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6,False,False,False,True,False,False
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,False,False,True,False,False,False

The arguments of `.join` are the following: 
````
DataFrame.join(self, other, on=None, how='left', lsuffix='', rsuffix='', sort=False)
````
With `how` we can specify which join method we want to use.

The how argument to merge specifies how to determine which keys are to be included in the resulting table. If a key combination does not appear in either the left or right tables, the values in the joined table will be NA. Here is a summary of the how options and their SQL equivalent names:

Merge method | SQL Join Name | Description
---|---|---
left| LEFT OUTER JOIN | Use keys from left frame only
right | RIGHT OUTER JOIN | Use keys from right frame only
outer | FULL OUTER JOIN | Use union of keys from both frames
inner | INNER JOIN | Use intersection of keys from both frames


You can also think of it as set theory and use Venn diagrams to illustrate what happens in each method.

![Join Methods](./images/join_types.png)

Let's now look at concat.
Similar to `join` we can  specify the method we want to use combine the datasets.

Different from join and merge, which by default operate on columns, concat can define whether to operate on columns or rows.
In the images below, you can see the differences, if axis is set as 0 or 1.

**Concat with axis=0:**
![Concat Axis 0](./images/concat_axis_0.png)

---

**Concat with axis=1:**
![Concat Axis 1](./images/concat_axis_1.png)

(The pictures were part of a blog post, which is no longer available)

In [6]:
joined_df2 = pd.concat([quality_dummies, wine_df], axis=1)
joined_df2.head()

,quality_3,quality_4,quality_5,quality_6,quality_7,quality_8,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,False,False,True,False,False,False,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,False,False,True,False,False,False,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,False,False,True,False,False,False,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,False,False,False,True,False,False,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,False,False,True,False,False,False,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

Let's read in a different data set, since we're looking at combining multiple data sources.

In [7]:
red_wines_df = pd.read_csv('data/winequality-red.csv', delimiter=';')
white_wines_df = pd.read_csv('data/winequality-white.csv', delimiter=';')

In [8]:
red_wines_df.columns

Index(['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol', 'quality'],
      dtype='object')

In [9]:
white_wines_df.columns

Index(['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol', 'quality'],
      dtype='object')

In [10]:
red_wines_quality_df = red_wines_df.groupby('quality').mean()['fixed acidity'].reset_index()
red_wines_quality_df.head()

   quality  fixed acidity
0        3       8.360000
1        4       7.779245
2        5       8.167254
3        6       8.347179
4        7       8.872362

In [16]:
white_wines_quality_df = white_wines_df.groupby('quality').mean()['fixed acidity'].reset_index()
white_wines_quality_df.head()

   quality  fixed acidity
0        3       7.600000
1        4       7.129448
2        5       6.933974
3        6       6.837671
4        7       6.734716

In [12]:
pd.merge(red_wines_quality_df, white_wines_quality_df, on=['quality'], suffixes=[' red', ' white'])

   quality  fixed acidity red  fixed acidity white
0        3           8.360000             7.600000
1        4           7.779245             7.129448
2        5           8.167254             6.933974
3        6           8.347179             6.837671
4        7           8.872362             6.734716
5        8           8.566667             6.657143

In [13]:
pd.concat([red_wines_quality_df, white_wines_quality_df['fixed acidity']], axis='columns', join='inner')

   quality  fixed acidity  fixed acidity
0        3       8.360000       7.600000
1        4       7.779245       7.129448
2        5       8.167254       6.933974
3        6       8.347179       6.837671
4        7       8.872362       6.734716
5        8       8.566667       6.657143

In [19]:
red_wines_quality_df.join(white_wines_quality_df, lsuffix='_red', rsuffix='_white')

   quality_red  fixed acidity_red  quality_white  fixed acidity_white
0            3           8.360000              3             7.600000
1            4           7.779245              4             7.129448
2            5           8.167254              5             6.933974
3            6           8.347179              6             6.837671
4            7           8.872362              7             6.734716
5            8           8.566667              8             6.657143

Please try out to generate the table above using the methods `.join()` and `.concat()`.

## Check your understanding

1. Please join the two given DataFrames (df1 and df2) along rows and merge with the third (df3) DataFrame along the common column id.

In [20]:
import pandas as pd

In [25]:
df1 = pd.DataFrame({
        'student_id': ['S1', 'S2', 'S3', 'S4', 'S5'],
        'name': ['Erika Raaf', 'Nadja Berens', 'Florentin Kleist', 'Dorothea Eibl', 'Gerhard Bihlmeier'], 
        'subject': ['Math', 'Biology', 'Biology', 'English', 'Philosophy']})
df2 = pd.DataFrame({
        'student_id': ['S6', 'S7', 'S8', 'S9', 'S10'],
        'name': ['Franz Xaver Schild', 'Ann-Kathrin Heiny', 'Jens Hüls', 'Vera Kagan', 'Paula Brodersen'], 
        'subject': ['Chemistry', 'Economics', 'Math', 'Math', 'Social Science']})
df3 = pd.DataFrame({
        'student_id': ['S1', 'S2', 'S3', 'S4', 'S5', 'S7', 'S8', 'S9', 'S10', 'S11', 'S12', 'S13'],
        'marks': [23, 45, 12, 67, 21, 55, 33, 14, 56, 83, 88, 12]})

In [33]:
pd.concat([df1, df2]).reset_index(drop=True)

  student_id                name         subject
0         S1          Erika Raaf            Math
1         S2        Nadja Berens         Biology
2         S3    Florentin Kleist         Biology
3         S4       Dorothea Eibl         English
4         S5   Gerhard Bihlmeier      Philosophy
5         S6  Franz Xaver Schild       Chemistry
6         S7   Ann-Kathrin Heiny       Economics
7         S8           Jens Hüls            Math
8         S9          Vera Kagan            Math
9        S10     Paula Brodersen  Social Science

In [34]:
con = pd.concat([df1, df2], axis='rows', ignore_index=True)
con

  student_id                name         subject
0         S1          Erika Raaf            Math
1         S2        Nadja Berens         Biology
2         S3    Florentin Kleist         Biology
3         S4       Dorothea Eibl         English
4         S5   Gerhard Bihlmeier      Philosophy
5         S6  Franz Xaver Schild       Chemistry
6         S7   Ann-Kathrin Heiny       Economics
7         S8           Jens Hüls            Math
8         S9          Vera Kagan            Math
9        S10     Paula Brodersen  Social Science

In [35]:
final_df = con.merge(df3, on='student_id', how='outer') # use outer to keep all records, else use left join since df1 and df2 have most of the records
final_df

   student_id                name         subject  marks
0          S1          Erika Raaf            Math   23.0
1         S10     Paula Brodersen  Social Science   56.0
2         S11                 NaN             NaN   83.0
3         S12                 NaN             NaN   88.0
4         S13                 NaN             NaN   12.0
5          S2        Nadja Berens         Biology   45.0
6          S3    Florentin Kleist         Biology   12.0
7          S4       Dorothea Eibl         English   67.0
8          S5   Gerhard Bihlmeier      Philosophy   21.0
9          S6  Franz Xaver Schild       Chemistry    NaN
10         S7   Ann-Kathrin Heiny       Economics   55.0
11         S8           Jens Hüls            Math   33.0
12         S9          Vera Kagan            Math   14.0

In [40]:
df3i = df3.set_index('student_id')
con_i = con.set_index('student_id')
final_df_join = con_i.join(df3i, how='outer')
final_df_join

                          name         subject  marks
student_id
S1                  Erika Raaf            Math   23.0
S10            Paula Brodersen  Social Science   56.0
S11                        NaN             NaN   83.0
S12                        NaN             NaN   88.0
S13                        NaN             NaN   12.0
S2                Nadja Berens         Biology   45.0
S3            Florentin Kleist         Biology   12.0
S4               Dorothea Eibl         English   67.0
S5           Gerhard Bihlmeier      Philosophy   21.0
S6          Franz Xaver Schild       Chemistry    NaN
S7           Ann-Kathrin Heiny       Economics   55.0
S8                   Jens Hüls            Math   33.0
S9                  Vera Kagan            Math   14.0