# Ressources:

- [Instructions](https://github.com/neuefische/de-week-4-Data-Processing-Fundamentals/blob/main/04_weekly_project/instructions.md)
- [Week 2 SQL](https://github.com/markusschlenker/nf-de-week-2-SQL---Data-Modeling/blob/main/01_introduction_to_sql/01_relational_database_design_principles.md)
- [Week 4 Solutions](https://github.com/neuefische/de-week-4-Data-Processing-Fundamentals/tree/solution)
- https://open-meteo.com/en/docs/historical-weather-api?daily=temperature_2m_max,temperature_2m_min
-

# Step 1: Make sure your container northwind_project_docker is up and running to perform below code

In [194]:
! pip install sqlalchemy pandas psycopg2-binary

Requirement already satisfied: sqlalchemy in /home/markus/.pyenv/versions/3.11.15/lib/python3.11/site-packages (2.0.48)
Requirement already satisfied: pandas in /home/markus/.pyenv/versions/3.11.15/lib/python3.11/site-packages (3.0.1)
Requirement already satisfied: psycopg2-binary in /home/markus/.pyenv/versions/3.11.15/lib/python3.11/site-packages (2.9.11)
Requirement already satisfied: greenlet>=1 in /home/markus/.pyenv/versions/3.11.15/lib/python3.11/site-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /home/markus/.pyenv/versions/3.11.15/lib/python3.11/site-packages (from sqlalchemy) (4.15.0)
Requirement already satisfied: numpy>=1.26.0 in /home/markus/.pyenv/versions/3.11.15/lib/python3.11/site-packages (from pandas) (2.4.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/markus/.pyenv/versions/3.11.15/lib/python3.11/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/markus/.pyenv/versions/3.11.15/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [195]:
from sqlalchemy import create_engine,text
import pandas as pd

In [203]:
username = "postgres"     
password = "admin"     
host = "localhost"            
port = "5434"                   
database = "db_northwind"


# Create the SQLAlchemy engine
connection_string = f"postgresql://{username}:{password}@{host}:{port}/{database}"
print(connection_string)
engine = create_engine(connection_string)


# Test the connection
with engine.begin() as conn:
    result = conn.execute(text("SELECT version();"))
    print(result.fetchone())

postgresql://postgres:admin@localhost:5434/db_northwind
('PostgreSQL 16.13 (Debian 16.13-1.pgdg13+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 14.2.0-19) 14.2.0, 64-bit',)

## 2.1 Retrieve order dates as list for API call

In [197]:
stmt = """
SELECT orderid, orderdate
FROM fct_tblnorthwind
"""

In [198]:
with engine.connect() as conn:
    result = conn.execute(text(stmt))
for r in result.fetchmany(5):
    print(r, type(r[1]))

(10249, datetime.date(1996, 7, 5)) <class 'datetime.date'>
(10251, datetime.date(1996, 7, 8)) <class 'datetime.date'>
(10251, datetime.date(1996, 7, 8)) <class 'datetime.date'>
(10251, datetime.date(1996, 7, 8)) <class 'datetime.date'>
(10252, datetime.date(1996, 7, 9)) <class 'datetime.date'>

In [199]:
df_order_info_min = pd.read_sql(stmt, con=engine)  #.drop_duplicates()
print(df_order_info_min.head())
print(df_order_info_min.info())
print(type(df_order_info_min.orderdate[0]))

   orderid   orderdate
0    10249  1996-07-05
1    10251  1996-07-08
2    10251  1996-07-08
3    10251  1996-07-08
4    10252  1996-07-09
<class 'pandas.DataFrame'>
RangeIndex: 985 entries, 0 to 984
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   orderid    985 non-null    int64
 1   orderdate  985 non-null    object
dtypes: int64(1), object(1)
memory usage: 15.5+ KB
None
<class 'datetime.date'>

In [200]:
order_dates = df_order_info_min.orderdate.unique()
print(len(order_dates))
print(order_dates[:5])

286
[datetime.date(1996, 7, 5) datetime.date(1996, 7, 8)
 datetime.date(1996, 7, 9) datetime.date(1996, 7, 10)
 datetime.date(1996, 7, 11)]

In [201]:
order_date_fmt = [d.strftime('%Y-%m-%d') for d in sorted(order_dates)]
order_date_fmt[:5] + ["..."] + order_date_fmt[-5:]

['1996-07-04',
 '1996-07-05',
 '1996-07-08',
 '1996-07-09',
 '1996-07-10',
 '...',
 '1997-08-04',
 '1997-08-05',
 '1997-08-06',
 '1997-08-07',
 '1997-08-08']

# 2.2 Fetch weather data

In [ ]:
! pip install openmeteo-requests
! pip install requests-cache retry-requests numpy pandas

Requirement already satisfied: openmeteo-requests in /home/markus/.pyenv/versions/3.11.15/lib/python3.11/site-packages (1.7.5)
Requirement already satisfied: niquests>=3.15.2 in /home/markus/.pyenv/versions/3.11.15/lib/python3.11/site-packages (from openmeteo-requests) (3.18.3)
Requirement already satisfied: openmeteo-sdk>=1.22.0 in /home/markus/.pyenv/versions/3.11.15/lib/python3.11/site-packages (from openmeteo-requests) (1.26.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /home/markus/.pyenv/versions/3.11.15/lib/python3.11/site-packages (from niquests>=3.15.2->openmeteo-requests) (3.4.5)
Requirement already satisfied: urllib3-future<3,>=2.13.903 in /home/markus/.pyenv/versions/3.11.15/lib/python3.11/site-packages (from niquests>=3.15.2->openmeteo-requests) (2.19.900)
Requirement already satisfied: wassima<3,>=1.0.1 in /home/markus/.pyenv/versions/3.11.15/lib/python3.11/site-packages (from niquests>=3.15.2->openmeteo-requests) (2.0.5)
Requirement already satisfied: h11<1.0.0,>=0.11.0 in /home/markus/.pyenv/versions/3.11.15/lib/python3.11/site-packages (from urllib3-future<3,>=2.13.903->niquests>=3.15.2->openmeteo-requests) (0.16.0)
Requirement already satisfied: jh2<6.0.0,>=5.0.3 in /home/markus/.pyenv/versions/3.11.15/lib/python3.11/site-packages (from urllib3-future<3,>=2.13.903->niquests>=3.15.2->openmeteo-requests) (5.0.10)
Requirement already satisfied: qh3<2.0.0,>=1.5.4 in /home/markus/.pyenv/versions/3.11.15/lib/python3.11/site-packages (from urllib3-future<3,>=2.13.903->niquests>=3.15.2->openmeteo-requests) (1.7.1)
Requirement already satisfied: flatbuffers==25.9.23 in /home/markus/.pyenv/versions/3.11.15/lib/python3.11/site-packages (from openmeteo-sdk>=1.22.0->openmeteo-requests) (25.9.23)
Requirement already satisfied: requests-cache in /home/markus/.pyenv/versions/3.11.15/lib/python3.11/site-packages (1.3.1)
Requirement already satisfied: retry-requests in /home/markus/.pyenv/versions/3.11.15/lib/python3.11/site-packages (2.0.0)
Requirement already satisfied: numpy in /home/markus/.pyenv/versions/3.11.15/lib/python3.11/site-packages (2.4.3)
Requirement already satisfied: pandas in /home/markus/.pyenv/versions/3.11.15/lib/python3.11/site-packages (3.0.1)
Requirement already satisfied: attrs>=21.2 in /home/markus/.pyenv/versions/3.11.15/lib/python3.11/site-packages (from requests-cache) (25.4.0)
Requirement already satisfied: cattrs>=22.2 in /home/markus/.pyenv/versions/3.11.15/lib/python3.11/site-packages (from requests-cache) (26.1.0)
Requirement already satisfied: platformdirs>=2.5 in /home/markus/.pyenv/versions/3.11.15/lib/python3.11/site-packages (from requests-cache) (4.9.4)
Requirement already satisfied: requests>=2.22 in /home/markus/.pyenv/versions/3.11.15/lib/python3.11/site-packages (from requests-cache) (2.32.5)
Requirement already satisfied: url-normalize>=2.0 in /home/markus/.pyenv/versions/3.11.15/lib/python3.11/site-packages (from requests-cache) (2.2.1)
Requirement already satisfied: urllib3>=1.25.5 in /home/markus/.pyenv/versions/3.11.15/lib/python3.11/site-packages (from requests-cache) (2.6.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/markus/.pyenv/versions/3.11.15/lib/python3.11/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: typing-extensions>=4.14.0 in /home/markus/.pyenv/versions/3.11.15/lib/python3.11/site-packages (from cattrs>=22.2->requests-cache) (4.15.0)
Requirement already satisfied: six>=1.5 in /home/markus/.pyenv/versions/3.11.15/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /home/markus/.pyenv/versions/3.11.15/lib/python3.11/site-packages (from requests>=2.22->requests-cache) (3.4.5)
Requirement already satisfied: idna<4,>=2.5 in /home/markus/.pyenv/versions/3.11.15/lib/python3.11/site-packages (from requests>=2.22->requests-cache) (3.11)
Requirement already satisfied: certifi>=2017.4.17 in /home/markus/.pyenv/versions/3.11.15/lib/python3.11/site-packages (from requests>=2.22->requests-cache) (2026.2.25)

In [10]:
import openmeteo_requests

import pandas as pd
import requests_cache
from retry_requests import retry

# Setup the Open-Meteo API client with cache and retry on error
cache_session = requests_cache.CachedSession('.cache', expire_after = -1)
retry_session = retry(cache_session, retries = 5, backoff_factor = 0.2)
openmeteo = openmeteo_requests.Client(session = retry_session)

# Make sure all required weather variables are listed here
# The order of variables in hourly or daily is important to assign them correctly below
url = "https://archive-api.open-meteo.com/v1/archive"
params = {
	"latitude": 52.5244,
	"longitude": 13.4105,
	"start_date":  min(order_date_fmt),  # "2010-01-01",
	"end_date":  max(order_date_fmt), # "2019-12-31",
	"daily": ["temperature_2m_max", "temperature_2m_min"],
	"hourly": "temperature_2m",
}
responses = openmeteo.weather_api(url, params = params)

# Process first location. Add a for-loop for multiple locations or weather models
response = responses[0]
print(f"Coordinates: {response.Latitude()}°N {response.Longitude()}°E")
print(f"Elevation: {response.Elevation()} m asl")
print(f"Timezone difference to GMT+0: {response.UtcOffsetSeconds()}s")

# Process hourly data. The order of variables needs to be the same as requested.
hourly = response.Hourly()
hourly_temperature_2m = hourly.Variables(0).ValuesAsNumpy()

hourly_data = {"date": pd.date_range(
	start = pd.to_datetime(hourly.Time(), unit = "s", utc = True),
	end =  pd.to_datetime(hourly.TimeEnd(), unit = "s", utc = True),
	freq = pd.Timedelta(seconds = hourly.Interval()),
	inclusive = "left"
)}

hourly_data["temperature_2m"] = hourly_temperature_2m

hourly_dataframe = pd.DataFrame(data = hourly_data)
print("\nHourly data\n", hourly_dataframe)

# Process daily data. The order of variables needs to be the same as requested.
daily = response.Daily()
daily_temperature_2m_max = daily.Variables(0).ValuesAsNumpy()
daily_temperature_2m_min = daily.Variables(1).ValuesAsNumpy()

daily_data = {"date": pd.date_range(
	start = pd.to_datetime(daily.Time(), unit = "s", utc = True),
	end =  pd.to_datetime(daily.TimeEnd(), unit = "s", utc = True),
	freq = pd.Timedelta(seconds = daily.Interval()),
	inclusive = "left"
)}

daily_data["temperature_2m_max"] = daily_temperature_2m_max
daily_data["temperature_2m_min"] = daily_temperature_2m_min

daily_dataframe = pd.DataFrame(data = daily_data)
print("\nDaily data\n", daily_dataframe)

Coordinates: 52.5483283996582°N 13.407821655273438°E
Elevation: 46.0 m asl
Timezone difference to GMT+0: 0s

Hourly data
                           date  temperature_2m
0    1996-07-04 00:00:00+00:00       14.287001
1    1996-07-04 01:00:00+00:00       14.137000
2    1996-07-04 02:00:00+00:00       13.987000
3    1996-07-04 03:00:00+00:00       13.937000
4    1996-07-04 04:00:00+00:00       14.437000
...                        ...             ...
9619 1997-08-08 19:00:00+00:00       22.187000
9620 1997-08-08 20:00:00+00:00       20.937000
9621 1997-08-08 21:00:00+00:00       20.087000
9622 1997-08-08 22:00:00+00:00       19.087000
9623 1997-08-08 23:00:00+00:00       18.237000

[9624 rows x 2 columns]

Daily data
                          date  temperature_2m_max  temperature_2m_min
0   1996-07-04 00:00:00+00:00           23.237000           13.937000
1   1996-07-05 00:00:00+00:00           23.487000           13.687000
2   1996-07-06 00:00:00+00:00           17.487000           11.637000
3   1996-07-07 00:00:00+00:00           18.636999           10.737000
4   1996-07-08 00:00:00+00:00           13.437000           12.287001
..                        ...                 ...                 ...
396 1997-08-04 00:00:00+00:00           25.386999           15.137000
397 1997-08-05 00:00:00+00:00           23.587000           15.737000
398 1997-08-06 00:00:00+00:00           23.536999           13.787001
399 1997-08-07 00:00:00+00:00           23.737000           15.087001
400 1997-08-08 00:00:00+00:00           26.087000           15.687000

[401 rows x 3 columns]

In [11]:
hourly_dataframe.info()

<class 'pandas.DataFrame'>
RangeIndex: 9624 entries, 0 to 9623
Data columns (total 2 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   date            9624 non-null   datetime64[s, UTC]
 1   temperature_2m  9624 non-null   float32
dtypes: datetime64[s, UTC](1), float32(1)
memory usage: 112.9 KB

## calc average temps

In [12]:
# Note: mean from hourly data is not the same as mean from daily data,
#       because of different time intervals and ambiguous treatment of edge values
#       --> using daily data
hourly_dataframe.groupby(hourly_dataframe.date.dt.date).temperature_2m.aggregate(['mean', 'min', 'max', 'count'])

                 mean        min        max  count
date
1996-07-04  18.226583  13.937000  23.237000     24
1996-07-05  19.116167  13.687000  23.487000     24
1996-07-06  14.545334  11.637000  17.487000     24
1996-07-07  14.807834  10.737000  18.636999     24
1996-07-08  12.772418  12.287001  13.437000     24
...               ...        ...        ...    ...
1997-08-04  20.870333  15.137000  25.386999     24
1997-08-05  19.395334  15.737000  23.587000     24
1997-08-06  19.080750  13.787001  23.536999     24
1997-08-07  19.526583  15.087001  23.737000     24
1997-08-08  21.020334  15.687000  26.087000     24

[401 rows x 4 columns]

In [13]:
daily_dataframe["temperature_2m_mean"] = (
    daily_dataframe["temperature_2m_max"]
    + daily_dataframe["temperature_2m_min"]) / 2
print(daily_dataframe.head())
print(daily_dataframe.info())

                       date  temperature_2m_max  temperature_2m_min  \
0 1996-07-04 00:00:00+00:00           23.237000           13.937000
1 1996-07-05 00:00:00+00:00           23.487000           13.687000
2 1996-07-06 00:00:00+00:00           17.487000           11.637000
3 1996-07-07 00:00:00+00:00           18.636999           10.737000
4 1996-07-08 00:00:00+00:00           13.437000           12.287001

   temperature_2m_mean
0               18.587
1               18.587
2               14.562
3               14.687
4               12.862
<class 'pandas.DataFrame'>
RangeIndex: 401 entries, 0 to 400
Data columns (total 4 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   date                 401 non-null    datetime64[s, UTC]
 1   temperature_2m_max   401 non-null    float32
 2   temperature_2m_min   401 non-null    float32
 3   temperature_2m_mean  401 non-null    float32
dtypes: datetime64[s, UTC](1), float32(3)
memory usage: 8.0 KB
None

## store in dedicated table

In [15]:
type(df_order_info_min.orderdate[0])

datetime.date

In [16]:
daily_dataframe.date = daily_dataframe.date.dt.date

In [17]:
print(daily_dataframe.head())
print(daily_dataframe.info())

         date  temperature_2m_max  temperature_2m_min  temperature_2m_mean
0  1996-07-04           23.237000           13.937000               18.587
1  1996-07-05           23.487000           13.687000               18.587
2  1996-07-06           17.487000           11.637000               14.562
3  1996-07-07           18.636999           10.737000               14.687
4  1996-07-08           13.437000           12.287001               12.862
<class 'pandas.DataFrame'>
RangeIndex: 401 entries, 0 to 400
Data columns (total 4 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   date                 401 non-null    object
 1   temperature_2m_max   401 non-null    float32
 2   temperature_2m_min   401 non-null    float32
 3   temperature_2m_mean  401 non-null    float32
dtypes: float32(3), object(1)
memory usage: 8.0+ KB
None

In [18]:
# test merge
pd.merge(df_order_info_min.head(), daily_dataframe[['date', "temperature_2m_mean"]], left_on="orderdate", right_on="date", how="inner")

   orderid   orderdate        date  temperature_2m_mean
0    10248  1996-07-04  1996-07-04               18.587
1    10248  1996-07-04  1996-07-04               18.587
2    10249  1996-07-05  1996-07-05               18.587
3    10251  1996-07-08  1996-07-08               12.862
4    10251  1996-07-08  1996-07-08               12.862

In [ ]:
with engine.begin() as conn:
    conn.execute(text("DROP TABLE IF EXISTS weather_data"))
    daily_dataframe[['date', "temperature_2m_mean"]].to_sql("weather_data", con=conn, index=False, if_exists="replace")

# 2.3 Web scrape quotes

In [ ]:
! pip install bs4 requests

Requirement already satisfied: bs4 in /home/markus/.pyenv/versions/3.11.15/lib/python3.11/site-packages (0.0.2)
Requirement already satisfied: beautifulsoup4 in /home/markus/.pyenv/versions/3.11.15/lib/python3.11/site-packages (from bs4) (4.14.3)
Requirement already satisfied: soupsieve>=1.6.1 in /home/markus/.pyenv/versions/3.11.15/lib/python3.11/site-packages (from beautifulsoup4->bs4) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in /home/markus/.pyenv/versions/3.11.15/lib/python3.11/site-packages (from beautifulsoup4->bs4) (4.15.0)

In [20]:
import requests
from bs4 import BeautifulSoup

In [21]:
url = "http://quotes.toscrape.com"

headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
                  "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
    "Accept-Language": "en-US,en;q=0.9",
}

In [22]:
response = requests.get(url, headers=headers)
print(response.status_code)
print(response.text[:500])

200
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Quotes to Scrape</title>
    <link rel="stylesheet" href="/static/bootstrap.min.css">
    <link rel="stylesheet" href="/static/main.css">


</head>
<body>
    <div class="container">
        <div class="row header-box">
            <div class="col-md-8">
                <h1>
                    <a href="/" style="text-decoration: none">Quotes to Scrape</a>
                </h1>
            </div>
            <div cla

In [23]:
soup = BeautifulSoup(response.text, "html.parser")

In [24]:
results = soup.find_all("span", class_="text")
print(len(results))
for r in results[:5]:
    print(r.text)

10
“The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.”
“It is our choices, Harry, that show what we truly are, far more than our abilities.”
“There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle.”
“The person, be it gentleman or lady, who has not pleasure in a good novel, must be intolerably stupid.”
“Imperfection is beauty, madness is genius and it's better to be absolutely ridiculous than absolutely boring.”

In [25]:
def scrape_quotes_page(url):
    response = requests.get(url, headers=headers)
    soup = BeautifulSoup(response.text, 'html.parser')
    results = soup.find_all("span", class_="text")
    return results

In [27]:
pages = [
    "http://quotes.toscrape.com",
    *[f"http://quotes.toscrape.com/page/{i}/" for i in range(2, 6)]
]

quotes = []
for page in pages:
    quotes.extend(scrape_quotes_page(page))
print(f"Total quotes scraped: {len(quotes)}")

Total quotes scraped: 50

## Add quotes to new table

In [35]:
stmt_create_tbl = """CREATE TABLE quotes_table (
    id SERIAL PRIMARY KEY,
    quote TEXT NOT NULL
)"""

with engine.begin() as conn:
    conn.execute(text("DROP TABLE IF EXISTS quotes_table"))
    conn.execute(text(stmt_create_tbl))
    for quote in quotes:
        conn.execute(text("INSERT INTO quotes_table (quote) VALUES (:quote)"), {"quote": quote.text})

In [36]:
with engine.connect() as conn:
    result = conn.execute(text("SELECT * FROM quotes_table LIMIT 5"))
    for r in result:
        print(r)

(1, '“The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.”')
(2, '“It is our choices, Harry, that show what we truly are, far more than our abilities.”')
(3, '“There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle.”')
(4, '“The person, be it gentleman or lady, who has not pleasure in a good novel, must be intolerably stupid.”')
(5, "“Imperfection is beauty, madness is genius and it's better to be absolutely ridiculous than absolutely boring.”")

# 2.4 Enrich fact table

## test getting random quote

In [43]:
stmt = """SELECT quote FROM quotes_table
ORDER BY RANDOM()
LIMIT 1"""
for _ in range(5):
    with engine.connect() as conn:
        result = conn.execute(text(stmt))
        print(result.fetchone())

("“You may not be her first, her last, or her only. She loved before she may love again. But if she loves you now, what else matters? She's not perfect ... (399 characters truncated) ... yze and don't expect more than she can give. Smile when she makes you happy, let her know when she makes you mad, and miss her when she's not there.”",)
('“Any fool can know. The point is to understand.”',)
('“Today you are You, that is truer than true. There is no one alive who is Youer than You.”',)
('“The real lover is the man who can thrill you by kissing your forehead or smiling into your eyes or just staring into space.”',)
('“Love does not begin and end the way we seem to think it does. Love is a battle, love is a war; love is a growing up.”',)

## Add new columns

In [ ]:
stmt ="""ALTER TABLE fct_tblnorthwind 
ADD COLUMN avg_temp_order_date Real,
ADD COLUMN random_quote TEXT
;"""
with engine.begin() as conn:
    conn.execute(text(stmt))

## Test combining columns

In [ ]:
# testing merge of tables into new columns as plain select

stmt = """SELECT 
    orderid, 
    --orderdate,
    --customerid,
    (SELECT temperature_2m_mean 
     FROM weather_data
     WHERE weather_data.date = fct.orderdate) AS avg_temp_order_date,
    (SELECT quote 
     FROM quotes_table
     WHERE orderid IS NOT NULL
     ORDER BY RANDOM()
     LIMIT 1) AS random_quote
FROM fct_tblnorthwind AS fct
;"""
with engine.connect() as conn:
    result = conn.execute(text(stmt))
for r in result.fetchmany(10):
    print(r)

(10248, 18.587, "“I have not failed. I've just found 10,000 ways that won't work.”")
(10248, 18.587, '“I have always imagined that Paradise will be a kind of library.”')
(10249, 18.587, '“Love does not begin and end the way we seem to think it does. Love is a battle, love is a war; love is a growing up.”')
(10251, 12.862, "“We read to know we're not alone.”")
(10251, 12.862, "“A wise girl kisses but doesn't love, listens but doesn't believe, and leaves before she is left.”")
(10251, 12.862, '“I may not have gone where I intended to go, but I think I have ended up where I needed to be.”')
(10252, 13.162001, '“It matters not what someone is born, but what they grow to be.”')
(10252, 13.162001, '“I love you without knowing how, or when, or from where. I love you simply, without problems or pride: I love you in this way because I do not know a ... (21 characters truncated) ... g but this, in which there is no I or you, so intimate that your hand upon my chest is my hand, so intimate that when I fall asleep your eyes close.”')
(10252, 13.162001, '“You can never get a cup of tea large enough or a book long enough to suit me.”')
(10253, 15.887001, '“Life is what happens to us while we are making other plans.”')

In [ ]:
# statement to add random_quote proposed chat - not using my prepared things, not updating temp yet
# - adds random quote to each order item line -> different quotes in on orderid
# - dummy external dependency in subquery is ESSENTIAL to force recalculation of RANDOM() for each row

stmt_update = """
UPDATE fct_tblnorthwind AS fct
SET random_quote = (
    SELECT quote 
    FROM quotes_table
    WHERE orderid IS NOT NULL
    ORDER BY RANDOM()
    LIMIT 1
);"""

# test without commit
with engine.connect() as conn:
    result = conn.execute(text(stmt_update))
    result = conn.execute(text("""SELECT orderid, random_quote, avg_temp_order_date 
        FROM fct_tblnorthwind 
        ORDER BY orderid
        LIMIT 5"""))
    for r in result:
        print(r)

(10248, "“This life is what you make it. No matter what, you're going to mess up sometimes, it's a universal truth. But the good part is you get to decide how ... (786 characters truncated) ...  So keep your head high, keep your chin up, and most importantly, keep smiling, because life's a beautiful thing and there's so much to smile about.”", None)
(10248, '“A day without sunshine is like, you know, night.”', None)
(10249, '“It is not a lack of love, but a lack of friendship that makes unhappy marriages.”', None)
(10251, '“It matters not what someone is born, but what they grow to be.”', None)
(10251, '“The real lover is the man who can thrill you by kissing your forehead or smiling into your eyes or just staring into space.”', None)

In [127]:
# statement to add temp to table
# - matching temp per orderdate
# - In PostgreSQL, the UPDATE statement with a FROM clause acts as an implicit JOIN. 
#   Furthermore, we can’t directly use INNER JOIN without using the WHERE clause. 
#   However, both perform similar functionality and produce the same output.
#   Source: Section 3.3 in https://www.baeldung.com/sql/update-data-id-match 

stmt_update = """
UPDATE fct_tblnorthwind
SET 
    avg_temp_order_date = weather_data.temperature_2m_mean
FROM weather_data
WHERE weather_data.date = fct_tblnorthwind.orderdate
;"""

# test without commit
with engine.connect() as conn:
    result = conn.execute(text(stmt_update))
    result = conn.execute(text("""SELECT orderid, orderdate, random_quote, avg_temp_order_date
        FROM fct_tblnorthwind  as fct
        ORDER BY orderid
        LIMIT 7"""))
    for r in result:
        print(r)

(10248, datetime.date(1996, 7, 4), None, 18.587)
(10248, datetime.date(1996, 7, 4), None, 18.587)
(10249, datetime.date(1996, 7, 5), None, 18.587)
(10251, datetime.date(1996, 7, 8), None, 12.862)
(10251, datetime.date(1996, 7, 8), None, 12.862)
(10251, datetime.date(1996, 7, 8), None, 12.862)
(10252, datetime.date(1996, 7, 9), None, 13.162001)

In [130]:
# statement to add temp and quote simultaneously based on orderdate
# - constant (=duplicate) quote per orderid 
#   -> not fulfilling assignment which requests random_quote in each order line

stmt_update = """
UPDATE fct_tblnorthwind
SET 
    random_quote = updated_data.random_quote,
    avg_temp_order_date = updated_data.avg_temp_order_date
FROM (
    SELECT 
        fct.orderid,
        (SELECT quote 
         FROM quotes_table
         WHERE fct.orderid IS NOT NULL
         ORDER BY RANDOM()
         LIMIT 1) AS random_quote,
        (SELECT temperature_2m_mean 
         FROM weather_data
         WHERE weather_data.date = fct.orderdate) AS avg_temp_order_date
    FROM fct_tblnorthwind AS fct
) AS updated_data
WHERE fct_tblnorthwind.orderid = updated_data.orderid
;"""

# test without commit
with engine.connect() as conn:
    result = conn.execute(text(stmt_update))
    result = conn.execute(text("""SELECT orderid, orderdate, random_quote, avg_temp_order_date 
        FROM fct_tblnorthwind 
        ORDER BY orderid
        LIMIT 5"""))
    for r in result:
        print(r)

(10248, datetime.date(1996, 7, 4), '“If you want your children to be intelligent, read them fairy tales. If you want them to be more intelligent, read them more fairy tales.”', 18.587)
(10248, datetime.date(1996, 7, 4), '“If you want your children to be intelligent, read them fairy tales. If you want them to be more intelligent, read them more fairy tales.”', 18.587)
(10249, datetime.date(1996, 7, 5), "“I have not failed. I've just found 10,000 ways that won't work.”", 18.587)
(10251, datetime.date(1996, 7, 8), '“The person, be it gentleman or lady, who has not pleasure in a good novel, must be intolerably stupid.”', 12.862)
(10251, datetime.date(1996, 7, 8), '“The person, be it gentleman or lady, who has not pleasure in a good novel, must be intolerably stupid.”', 12.862)

In [131]:
# alternative with CTE - equivalent to previous solution with subquery
stmt_update = """
WITH updated_data AS (
    SELECT 
        fct.orderid,
        (SELECT quote 
         FROM quotes_table
         WHERE fct.orderid IS NOT NULL
         ORDER BY RANDOM()
         LIMIT 1) AS random_quote,
        (SELECT temperature_2m_mean 
         FROM weather_data
         WHERE weather_data.date = fct.orderdate) AS avg_temp_order_date
    FROM fct_tblnorthwind AS fct
)
UPDATE fct_tblnorthwind
SET 
    random_quote = updated_data.random_quote,
    avg_temp_order_date = updated_data.avg_temp_order_date
FROM updated_data
WHERE fct_tblnorthwind.orderid = updated_data.orderid
;"""

# test without commit
with engine.connect() as conn:
    result = conn.execute(text(stmt_update))
    result = conn.execute(text("""SELECT orderid, orderdate, random_quote, avg_temp_order_date 
        FROM fct_tblnorthwind 
        ORDER BY orderid
        LIMIT 5"""))
    for r in result:
        print(r)

(10248, datetime.date(1996, 7, 4), '“Beauty is in the eye of the beholder and it may be necessary from time to time to give a stupid or misinformed beholder a black eye.”', 18.587)
(10248, datetime.date(1996, 7, 4), '“Beauty is in the eye of the beholder and it may be necessary from time to time to give a stupid or misinformed beholder a black eye.”', 18.587)
(10249, datetime.date(1996, 7, 5), '“It takes a great deal of bravery to stand up to our enemies, but just as much to stand up to our friends.”', 18.587)
(10251, datetime.date(1996, 7, 8), '“It is impossible to live without failing at something, unless you live so cautiously that you might as well not have lived at all - in which case, you fail by default.”', 12.862)
(10251, datetime.date(1996, 7, 8), '“It is impossible to live without failing at something, unless you live so cautiously that you might as well not have lived at all - in which case, you fail by default.”', 12.862)

## Solution for 2.4 requires separate update for temp and quote

- Quote shall be fully random for each line
- temp is connected to date and therefore at least constant (duplicate) for the same orderid

In [132]:
# statement to add temp to table as tested above
# - matching temp per orderdate
# - In PostgreSQL, the UPDATE statement with a FROM clause acts as an implicit JOIN. 
#   Furthermore, we can’t directly use INNER JOIN without using the WHERE clause. 
#   However, both perform similar functionality and produce the same output.
#   Source: Section 3.3 in https://www.baeldung.com/sql/update-data-id-match 

stmt_update = """
UPDATE fct_tblnorthwind
SET 
    avg_temp_order_date = weather_data.temperature_2m_mean
FROM weather_data
WHERE weather_data.date = fct_tblnorthwind.orderdate
;"""

# transaction WITH commit if without error
with engine.begin() as conn:
    result = conn.execute(text(stmt_update))
    result = conn.execute(text("""SELECT orderid, orderdate, random_quote, avg_temp_order_date
        FROM fct_tblnorthwind  as fct
        ORDER BY orderid
        LIMIT 7"""))
    for r in result:
        print(r)

(10248, datetime.date(1996, 7, 4), None, 18.587)
(10248, datetime.date(1996, 7, 4), None, 18.587)
(10249, datetime.date(1996, 7, 5), None, 18.587)
(10251, datetime.date(1996, 7, 8), None, 12.862)
(10251, datetime.date(1996, 7, 8), None, 12.862)
(10251, datetime.date(1996, 7, 8), None, 12.862)
(10252, datetime.date(1996, 7, 9), None, 13.162001)

In [148]:
# statement to add quote

# solution proposed by chat:
stmt_update_CHAT = """
UPDATE fct_tblnorthwind AS fct
SET random_quote = (
    SELECT quote 
    FROM quotes_table
    WHERE orderid IS NOT NULL
    ORDER BY RANDOM()
    LIMIT 1
);"""

# My solution is more verbose and probably less performant then the solution proposed by chat:
# - Note: match on (orderid, productid) to have a unique line, otherwise
#         orderid lines will only use the first random quote
stmt_update = """
UPDATE fct_tblnorthwind
SET 
    random_quote = updated_data.random_quote
FROM (
    SELECT 
        fct.orderid,
        fct.productid,
        (SELECT quote 
         FROM quotes_table
         WHERE fct.orderdate IS NOT NULL
         ORDER BY RANDOM()
         LIMIT 1) AS random_quote
    FROM fct_tblnorthwind AS fct
) AS updated_data
WHERE fct_tblnorthwind.orderid = updated_data.orderid
    AND fct_tblnorthwind.productid = updated_data.productid
;"""


# transaction WITH commit if without error
with engine.begin() as conn:
    result = conn.execute(text(stmt_update))
    result = conn.execute(text("""SELECT orderid, orderdate, random_quote, avg_temp_order_date 
        FROM fct_tblnorthwind 
        ORDER BY orderid
        LIMIT 5"""))
    for r in result:
        print(r)

(10248, datetime.date(1996, 7, 4), "“We read to know we're not alone.”", 18.587)
(10248, datetime.date(1996, 7, 4), '“It matters not what someone is born, but what they grow to be.”', 18.587)
(10249, datetime.date(1996, 7, 5), '“If you judge people, you have no time to love them.”', 18.587)
(10251, datetime.date(1996, 7, 8), '“There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle.”', 12.862)
(10251, datetime.date(1996, 7, 8), '“Only in the darkness can you see the stars.”', 12.862)

# Step 3 Create reporting tables

Use Views used e.g. in [week 2 weekly projects instructions PART 5](https://github.com/markusschlenker/nf-de-week-2-SQL---Data-Modeling/blob/main/05_weekly_project/instructions.md)

## Supporting queries to find information about existing tables

- find all column names in all tables in plain SQL ([SO ref](https://stackoverflow.com/a/26553544))
- find column names in a table using SQL or pandas

Important column names in "information_schema.columns" are e.g. (not exclusively!):

- 'ordinal_position'
- 'table_name'
- 'column_name'

Note: this is the view 'columns' on the 'information_schema'.
See also the official [docs](https://www.postgresql.org/docs/current/infoschema-columns.html):

> The view columns contains information about all table columns (or view columns) in the database. System columns (ctid, etc.) are not included. Only those columns are shown that the **current user has access to** (by way of being the owner or having some privilege).

In [168]:
stmt = """SELECT C.TABLE_NAME, C.COLUMN_NAME
FROM INFORMATION_SCHEMA.COLUMNS C
WHERE EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES T 
              WHERE T.TABLE_TYPE='BASE TABLE' AND C.TABLE_NAME=T.TABLE_NAME)
ORDER BY C.TABLE_NAME, C.ORDINAL_POSITION"""

with engine.connect() as conn:
    result = conn.execute(text(stmt))
    results = result.fetchall()
    for r in results[0:5] + ["..."] + results[-5:]:
        print(r)

('fct_tblnorthwind', 'orderid')
('fct_tblnorthwind', 'customerid')
('fct_tblnorthwind', 'employeeid')
('fct_tblnorthwind', 'orderdate')
('fct_tblnorthwind', 'requireddate')
...
('tblnorthwind_error', 'supplierscontactname')
('tblnorthwind_error', 'supplierscontacttitle')
('tblnorthwind_error', 'error_reason')
('weather_data', 'date')
('weather_data', 'temperature_2m_mean')

In [ ]:
stmt = """SELECT *
  FROM information_schema.columns

 WHERE table_schema = 'public'
   AND table_name   = 'fct_tblnorthwind'

ORDER BY ordinal_position
     ;"""

df_info_schema = pd.read_sql(stmt, engine)
print(df_info_schema.columns)
print(list(df_info_schema.column_name))

Index(['table_catalog', 'table_schema', 'table_name', 'column_name',
       'ordinal_position', 'column_default', 'is_nullable', 'data_type',
       'character_maximum_length', 'character_octet_length',
       'numeric_precision', 'numeric_precision_radix', 'numeric_scale',
       'datetime_precision', 'interval_type', 'interval_precision',
       'character_set_catalog', 'character_set_schema', 'character_set_name',
       'collation_catalog', 'collation_schema', 'collation_name',
       'domain_catalog', 'domain_schema', 'domain_name', 'udt_catalog',
       'udt_schema', 'udt_name', 'scope_catalog', 'scope_schema', 'scope_name',
       'maximum_cardinality', 'dtd_identifier', 'is_self_referencing',
       'is_identity', 'identity_generation', 'identity_start',
       'identity_increment', 'identity_maximum', 'identity_minimum',
       'identity_cycle', 'is_generated', 'generation_expression',
       'is_updatable'],
      dtype='str')
['orderid', 'customerid', 'employeeid', 'orderdate', 'requireddate', 'shippeddate', 'shipvia', 'freight', 'productid', 'unitprice', 'quantity', 'discount', 'companyname', 'contactname', 'contacttitle', 'employeeslastname', 'employeesfirstname', 'employeestitle', 'productname', 'supplierid', 'categoryid', 'quantityperunit', 'unitprice1', 'unitsinstock', 'unitsonorder', 'reorderlevel', 'discontinued', 'categoryname', 'supplierscompanyname', 'supplierscontactname', 'supplierscontacttitle', 'error_reason', 'load_date', 'avg_temp_order_date', 'random_quote']

In [180]:
df_info_schema[:5]

,table_catalog,table_schema,table_name,column_name,ordinal_position,column_default,is_nullable,data_type,character_maximum_length,character_octet_length,...,is_identity,identity_generation,identity_start,identity_increment,identity_maximum,identity_minimum,identity_cycle,is_generated,generation_expression,is_updatable
0,db_northwind,public,fct_tblnorthwind,orderid,1,NaN,NO,bigint,None,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,YES
1,db_northwind,public,fct_tblnorthwind,customerid,2,NaN,YES,text,None,1.073742e+09,...,NO,None,None,None,None,None,NO,NEVER,None,YES
2,db_northwind,public,fct_tblnorthwind,employeeid,3,NaN,YES,bigint,None,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,YES
3,db_northwind,public,fct_tblnorthwind,orderdate,4,NaN,YES,date,None,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,YES
4,db_northwind,public,fct_tblnorthwind,requireddate,5,NaN,YES,date,None,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,YES

In [185]:
list(df_info_schema.column_name)

['orderid',
 'customerid',
 'employeeid',
 'orderdate',
 'requireddate',
 'shippeddate',
 'shipvia',
 'freight',
 'productid',
 'unitprice',
 'quantity',
 'discount',
 'companyname',
 'contactname',
 'contacttitle',
 'employeeslastname',
 'employeesfirstname',
 'employeestitle',
 'productname',
 'supplierid',
 'categoryid',
 'quantityperunit',
 'unitprice1',
 'unitsinstock',
 'unitsonorder',
 'reorderlevel',
 'discontinued',
 'categoryname',
 'supplierscompanyname',
 'supplierscontactname',
 'supplierscontacttitle',
 'error_reason',
 'load_date',
 'avg_temp_order_date',
 'random_quote']

## Reporting View "Customers"

In [ ]:
stmt = """
CREATE OR REPLACE VIEW "Customers" AS

SELECT 
    customerid,
    companyname,
    contactname,
    contacttitle,
    random_quote

FROM fct_tblnorthwind
"""

with engine.begin() as conn:
    conn.execute(text(stmt))
    df = pd.read_sql("""SELECT * FROM "Customers" """, conn)
df

,customerid,companyname,contactname,contacttitle,random_quote
0,TOMSP,Toms Spezialitäten,Karin Josephs,Marketing Manager,"“If you judge people, you have no time to love..."
1,VICTE,Victuailles en stock,Mary Saveley,Sales Agent,“There are only two ways to live your life. On...
2,VICTE,Victuailles en stock,Mary Saveley,Sales Agent,“Only in the darkness can you see the stars.”
3,VICTE,Victuailles en stock,Mary Saveley,Sales Agent,“All you need is love. But a little chocolate ...
4,SUPRD,Suprêmes délices,Pascale Cartrain,Accounting Manager,"“Imperfection is beauty, madness is genius and..."
...,...,...,...,...,...
980,THECR,The Cracker Box,Liu Wong,Marketing Assistant,“Life is what happens to us while we are makin...
981,THECR,The Cracker Box,Liu Wong,Marketing Assistant,"“Imperfection is beauty, madness is genius and..."
982,ANATR,Ana Trujillo Emparedados y helados,Ana Trujillo,Owner,"“I like nonsense, it wakes up the brain cells...."
983,ANATR,Ana Trujillo Emparedados y helados,Ana Trujillo,Owner,"“If you judge people, you have no time to love..."
984,ANATR,Ana Trujillo Emparedados y helados,Ana Trujillo,Owner,"“Imperfection is beauty, madness is genius and..."

## Reporting View "Orders"

In [193]:
stmt = """
CREATE OR REPLACE VIEW "Orders" AS

SELECT 
    orderid,
    customerid,
    orderdate,
    requireddate,
    shippeddate,
    quantity,
    avg_temp_order_date

FROM fct_tblnorthwind
"""

with engine.begin() as conn:
    conn.execute(text(stmt))
    df = pd.read_sql("""SELECT * FROM "Orders" """, conn)
df

,orderid,customerid,orderdate,requireddate,shippeddate,quantity,avg_temp_order_date
0,10249,TOMSP,1996-07-05,1996-08-16,1996-07-10,9,18.587000
1,10251,VICTE,1996-07-08,1996-08-05,1996-07-15,6,12.862000
2,10251,VICTE,1996-07-08,1996-08-05,1996-07-15,15,12.862000
3,10251,VICTE,1996-07-08,1996-08-05,1996-07-15,20,12.862000
4,10252,SUPRD,1996-07-09,1996-08-06,1996-07-11,40,13.162001
...,...,...,...,...,...,...,...
980,10624,THECR,1997-08-07,1997-09-04,1997-08-19,10,19.412000
981,10624,THECR,1997-08-07,1997-09-04,1997-08-19,6,19.412000
982,10625,ANATR,1997-08-08,1997-09-05,1997-08-14,3,20.887001
983,10625,ANATR,1997-08-08,1997-09-05,1997-08-14,5,20.887001
984,10625,ANATR,1997-08-08,1997-09-05,1997-08-14,10,20.887001